server_names = ['ea-dns.rubyfish.cn', 'uw-dns.rubyfish.cn']
listen_addresses = ['127.0.0.1:5533']
doh_servers = true
fallback_resolvers = ['114.114.114.114:53']

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_max_ttl = 600

[static]
  [static.'ea-dns.rubyfish.cn']
  stamp = 'sdns://AgUAAAAAAAAADzExNS4xNTkuMTMxLjIzMAASZWEtZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'
  [static.'uw-dns.rubyfish.cn']
  stamp = 'sdns://AgUAAAAAAAAADzExNS4xNTkuMTMxLjIzMAASdXctZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'
  [static.'geekdns-e']
  stamp = 'sdns://AgMAAAAAAAAADTQ3LjEwMS4xMzYuMzcgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgOZWRucy4yMzNweS5jb20KL2Rucy1xdWVyeQ'
  [static.'geekdns-n']
  stamp = 'sdns://AgMAAAAAAAAADzExNC4xMTUuMjQwLjE3NSA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OA5uZG5zLjIzM3B5LmNvbQovZG5zLXF1ZXJ5'
  [static.'geekdns-s']
  stamp = 'sdns://AgMAAAAAAAAADTExOS4yOS4xMDcuODUgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgOc2Rucy4yMzNweS5jb20KL2Rucy1xdWVyeQ'
  [static.'geekdns-w']
  stamp = 'sdns://AgMAAAAAAAAADjExOC4yNC4yMDguMTk3ID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4DndkbnMuMjMzcHkuY29tCi9kbnMtcXVlcnk'
  [static.'geekdns-ru']
  stamp = 'sdns://AgcAAAAAAAAADTkxLjE4OC4yMjMuNjYAEHJ1LWRucy4yMzNweS5jb20KL2Rucy1xdWVyeQ'
  [static.'geekdns-hk']
  stamp = 'sdns://AgcAAAAAAAAADTExOS4yOC42OC4xNDIAEGhrLWRucy4yMzNweS5jb20KL2Rucy1xdWVyeQ'
  [static.'geekdns-de']
  stamp = 'sdns://AgcAAAAAAAAADjE3Ni45Ni4xMzguMjExABBkZS1kbnMuMjMzcHkuY29tCi9kbnMtcXVlcnk'
  [static.'rixcloud']
  stamp = 'sdns://AgUAAAAAAAAADjM0LjEyMC4xMjcuMTY3ABBkb2gucml4Y2xvdWQuZGV2Ci9kbnMtcXVlcnk'
  [static.'iij.jp']
  stamp = 'sdns://AgUAAAAAAAAACjEwMy4yLjU3LjYAEXB1YmxpYy5kbnMuaWlqLmpwCi9kbnMtcXVlcnk'
  [static.'blahdns']
  stamp = 'sdns://AgUAAAAAAAAACzQ1LjMyLjU1Ljk0ABJkb2gtanAuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'
