server_names = ['cloudflare']
listen_addresses = ['127.0.0.1:5533']
doh_servers = true
fallback_resolvers = ['114.114.114.114:53']

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_max_ttl = 600

[static]
  [static.'cloudflare']
  stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'
